name: Deploy website
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Deploy website
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}